apiVersion: 1

# Global settings for all alerts
global:
  resolve_timeout: 5m
  # Default SMTP configuration (can be overridden in notification policies)
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alerts@magflow.example.com'
  smtp_auth_username: 'alerting@example.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Alert manager configuration
alertmanager_config: |
  global:
    smtp_smarthost: 'smtp.example.com:587'
    smtp_from: 'alerts@magflow.example.com'
    smtp_auth_username: '${SMTP_USER}'
    smtp_auth_password: '${SMTP_PASSWORD}'
    smtp_require_tls: true

  route:
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    receiver: 'team-email'

  receivers:
  - name: 'team-email'
    email_configs:
    - to: 'devops@magflow.example.com'
      send_resolved: true
      headers:
        subject: '{{ template "email.default.subject" . }}'
      html: '{{ template "email.default.html" . }}'

  - name: 'critical-alerts'
    email_configs:
    - to: 'oncall@magflow.example.com'
      send_resolved: true
      headers:
        subject: 'CRITICAL: {{ template "email.default.subject" . }}'
      html: '{{ template "email.default.html" . }}'
