name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOCKER_IMAGE: /magflow
  K8S_NAMESPACE_DEV: magflow-dev
  K8S_NAMESPACE_PROD: magflow-prod
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
        
    - name: Run tests
      run: |
        pytest tests/ --cov=app --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

  build-and-push:
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          ${{ env.DOCKER_IMAGE }}:latest
          
  deploy-dev:
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DEV }}
        
    - name: Deploy to Development
      run: |
        kubectl config use-context ${{ env.K8S_NAMESPACE_DEV }}
        kubectl apply -k deploy/k8s/overlays/development
        
  deploy-prod:
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up kubectl
      uses: azure/k8s-set-context@v3
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_PROD }}
        
    - name: Deploy to Production
      run: |
        kubectl config use-context ${{ env.K8S_NAMESPACE_PROD }}
        kubectl apply -k deploy/k8s/overlays/production
        
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/magflow-app -n ${{ env.K8S_NAMESPACE_PROD }} --timeout=300s
        
    - name: Run smoke tests
      run: |
        # Add your smoke tests here
        echo "Running smoke tests..."
        # Example: curl -sSf http://your-production-url/health
        
  notify:
    needs: [deploy-dev, deploy-prod]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Send notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_COLOR: ${{ job.status == 'success' && '#36a64f' || '#ff0000' }}
        SLACK_TITLE: 'Deployment ${{ job.status }}: ${{ github.repository }}@${{ github.ref }}'
        SLACK_MESSAGE: 'Deployment ${{ job.status }} for commit ${{ github.sha }}'
        SLACK_USERNAME: GitHub Actions
        SLACK_ICON: https://github.githubassets.com/favicon.ico
