name: Security Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Cancel previous runs for the same PR
defaults:
  run:
    shell: bash

jobs:
  pip-audit:
    name: Dependency Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: python -m pip install --upgrade pip pip-audit

      - name: Run pip-audit
        run: |
          pip-audit --strict --ignore-vuln GHSA-36x3-8jfw-8q6x --ignore-vuln PYSEC-2022-43012 --ignore-vuln PYSEC-2025-49  # Ignoring vulnerabilities that are being addressed

  codeql-analysis:
    name: CodeQL Analysis
    permissions:
      security-events: write
      actions: read
      contents: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: python
          queries: security-extended,security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:python"
          upload: true
          output: codeql-results.sarif

  bandit-scan:
    name: Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r app/ -ll -f json -o bandit-results.json || true

      - name: Upload Bandit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-results
          path: bandit-results.json
          retention-days: 7

  # This job runs after all security checks complete
  security-report:
    name: Security Report
    needs: [pip-audit, codeql-analysis, bandit-scan]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check if any security check failed
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "One or more security checks failed. Please check the logs for details."
          exit 1
