global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'magflow-erp'
    static_configs:
      - targets: ['app:8001']  # Metrics port
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # eMAG Integration specific monitoring
  - job_name: 'emag-integration-health'
    static_configs:
      - targets: ['app:8000']  # Health check endpoint
    scrape_interval: 60s
    metrics_path: /health
    params:
      format: ['json']

  - job_name: 'emag-api-monitor'
    static_configs:
      - targets: ['app:8000']
    scrape_interval: 30s
    metrics_path: /api/v1/emag/integration/status
    params:
      format: ['json']
