apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels to apply to all resources
commonLabels:
  app: magflow
  tier: backend
  environment: production

# Namespace to deploy to
namespace: magflow

# Resources to include
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

# Secret generation (for local development only, use external secrets in production)
# secrets:
#   - name: magflow-secrets
#     type: Opaque
#     files:
#       - secrets/database-url
#       - secrets/secret-key
#       - secrets/smtp-credentials

# ConfigMap generator (alternative to external files)
# configMapGenerator:
#   - name: magflow-config
#     literals:
#       - ENVIRONMENT=production
#       - DEBUG=0
#       - LOG_LEVEL=INFO

# Image overrides for different environments
images:
  - name: magflow-app
    newName: your-registry/magflow
    newTag: latest

# Patches for different environments
patches:
  - path: patches/dev-patch.yaml
    target:
      kind: Deployment
      name: magflow-app
  - path: patches/prod-patch.yaml
    target:
      kind: Deployment
      name: magflow-app

# Replicas for different environments
replicas:
  - name: magflow-app
    count: 3

# Resource limits and requests
resources:
  - name: magflow-app
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

# Common annotations
commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: "kustomize"
  app.kubernetes.io/part-of: "magflow"

# Add a suffix to all resource names
nameSuffix: -prod

# Add a prefix to all resource names
# namePrefix: dev-

# Add a common label to all resources
# labels:
#   - pairs:
#       environment: production

# Add a common annotation to all resources
# annotations:
#   - pairs:
#       owner: devops-team
