apiVersion: 1
datasources:
  - name: MagFlow Postgres
    type: postgres
    access: proxy
    url: db:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASS}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      timescaledb: false
    isDefault: false
    editable: true
