receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
    spike_limit_mib: 500
  batch:
    timeout: 1s
    send_batch_size: 1024

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
    check_collector_pipeline:
      enabled: true
      interval: 5m
      exporter_failure_threshold: 5
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: magflow
    const_labels:
      service: magflow-api
      environment: development
    add_metric_suffixes: false
    metric_expiration: 10m
    resource_to_telemetry_conversion:
      enabled: true
  
  otlp:
    endpoint: "otel-collector:4317"
    tls:
      insecure: true

service:
  extensions: [health_check, pprof, zpages]
  telemetry:
    metrics:
      level: detailed
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
